// <auto-generated />
using System;
using Group3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Group3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220822202649_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Group3.Models.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "937e8cad-5606-4fad-be6e-d8b92475333c",
                            ConcurrencyStamp = "ca2bf305-b2e2-4e3f-8081-b8ec13c1f203",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "83640dd0-67f5-4c15-882f-3297ca8c43a8",
                            ConcurrencyStamp = "d45fbb1f-21bf-4f39-a84f-548b771e8f51",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "59916144-f72b-4c5b-bf51-9c3a40f0deb1",
                            ConcurrencyStamp = "41afb885-243d-47cc-8e20-98741087ccaf",
                            Name = "Moderator",
                            NormalizedName = "MODERATOR"
                        });
                });

            modelBuilder.Entity("Group3.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "6a1253ea-c5ec-496f-a4c4-b984e20f9507",
                            AccessFailedCount = 0,
                            Birthdate = new DateTime(1964, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "3b0938ca-fbce-46e4-a2e8-0a93611b2df7",
                            Email = "admin@fakemail.net",
                            EmailConfirmed = false,
                            FirstName = "John",
                            LastName = "Doe",
                            Location = "America",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@FAKEMAIL.NET",
                            NormalizedUserName = "ADMIN@FAKEMAIL.NET",
                            PasswordHash = "AQAAAAEAACcQAAAAEJO8P+CQ5hqJJE8HF1QMbEmbxZ7+q+hOXJ1h9akmASc+DVM0chXP98n7QHnoTEjunQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "335d2746-1594-4326-a884-4d4241758aec",
                            TwoFactorEnabled = false,
                            UserName = "admin@fakemail.net"
                        },
                        new
                        {
                            Id = "73cb7202-145f-42cb-867e-a9082bbfeb94",
                            AccessFailedCount = 0,
                            Birthdate = new DateTime(1993, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "8c30cdf8-0096-4b3e-be31-eff4dad8554f",
                            Email = "sara@fakemail.net",
                            EmailConfirmed = false,
                            FirstName = "Sara",
                            LastName = "Svensson",
                            Location = "Danmark",
                            LockoutEnabled = false,
                            NormalizedEmail = "SARA@FAKEMAIL.NET",
                            NormalizedUserName = "SARA@FAKEMAIL.NET",
                            PasswordHash = "AQAAAAEAACcQAAAAECNYnQxA1mzYb6UtmxdSvD4wZUM5Oqq+5d9wxX/AEQfaxrLZGy7CEYOKpJ54wkx8Ow==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ca30128a-309c-415d-95fa-75ba109aaeb4",
                            TwoFactorEnabled = false,
                            UserName = "sara@fakemail.net"
                        },
                        new
                        {
                            Id = "a27dfaaa-183e-46ab-aade-65c082a16a2e",
                            AccessFailedCount = 0,
                            Birthdate = new DateTime(1985, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "7d44da47-3557-43d2-a914-027c5b75d34f",
                            Email = "bertil@fakemail.net",
                            EmailConfirmed = false,
                            FirstName = "Bertil",
                            LastName = "Johansson",
                            Location = "Sweden",
                            LockoutEnabled = false,
                            NormalizedEmail = "BERTIL@FAKEMAIL.NET",
                            NormalizedUserName = "BERTIL@FAKEMAIL.NET",
                            PasswordHash = "AQAAAAEAACcQAAAAELaY7CMiId+a/haBQS7IJjcnhAENUmKQq9woaC/A4E53bYJ2NO5pGLZj1emqNNQz8w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "56c4f2cf-ca9b-4e3d-ae0a-f85f83da23ea",
                            TwoFactorEnabled = false,
                            UserName = "bertil@fakemail.net"
                        });
                });

            modelBuilder.Entity("Group3.Models.ApplicationUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "6a1253ea-c5ec-496f-a4c4-b984e20f9507",
                            RoleId = "937e8cad-5606-4fad-be6e-d8b92475333c"
                        },
                        new
                        {
                            UserId = "73cb7202-145f-42cb-867e-a9082bbfeb94",
                            RoleId = "83640dd0-67f5-4c15-882f-3297ca8c43a8"
                        },
                        new
                        {
                            UserId = "a27dfaaa-183e-46ab-aade-65c082a16a2e",
                            RoleId = "59916144-f72b-4c5b-bf51-9c3a40f0deb1"
                        });
                });

            modelBuilder.Entity("Group3.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("UserGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Description = "Breaking news here!",
                            Name = "News",
                            UserGroupId = 0
                        },
                        new
                        {
                            Id = -2,
                            Description = "Javascript, React and more.",
                            Name = "Frontend",
                            UserGroupId = 0
                        },
                        new
                        {
                            Id = -3,
                            Description = "C++ and C#",
                            Name = "Backend",
                            UserGroupId = 0
                        },
                        new
                        {
                            Id = -4,
                            Description = "En grupp av testare.",
                            Name = "Testgruppen",
                            UserGroupId = 0
                        },
                        new
                        {
                            Id = -5,
                            Description = "Systems, programs & other tools for software development.",
                            Name = "Systems",
                            UserGroupId = 0
                        },
                        new
                        {
                            Id = -6,
                            Description = "Our own projects and ideas.",
                            Name = "Projects",
                            UserGroupId = 0
                        },
                        new
                        {
                            Id = -7,
                            Description = "Anything else.",
                            Name = "Other",
                            UserGroupId = 0
                        });
                });

            modelBuilder.Entity("Group3.Models.Conversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Conversations");

                    b.HasData(
                        new
                        {
                            Id = -1
                        },
                        new
                        {
                            Id = -2
                        },
                        new
                        {
                            Id = -3
                        });
                });

            modelBuilder.Entity("Group3.Models.ConversationParticipation", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("UserId", "ConversationId");

                    b.HasIndex("ConversationId");

                    b.ToTable("ConversationParticipations");

                    b.HasData(
                        new
                        {
                            UserId = "6a1253ea-c5ec-496f-a4c4-b984e20f9507",
                            ConversationId = -1,
                            Id = -1
                        },
                        new
                        {
                            UserId = "73cb7202-145f-42cb-867e-a9082bbfeb94",
                            ConversationId = -1,
                            Id = -2
                        },
                        new
                        {
                            UserId = "a27dfaaa-183e-46ab-aade-65c082a16a2e",
                            ConversationId = -1,
                            Id = -3
                        },
                        new
                        {
                            UserId = "6a1253ea-c5ec-496f-a4c4-b984e20f9507",
                            ConversationId = -2,
                            Id = -4
                        },
                        new
                        {
                            UserId = "a27dfaaa-183e-46ab-aade-65c082a16a2e",
                            ConversationId = -2,
                            Id = -6
                        },
                        new
                        {
                            UserId = "73cb7202-145f-42cb-867e-a9082bbfeb94",
                            ConversationId = -3,
                            Id = -7
                        },
                        new
                        {
                            UserId = "a27dfaaa-183e-46ab-aade-65c082a16a2e",
                            ConversationId = -3,
                            Id = -8
                        });
                });

            modelBuilder.Entity("Group3.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(10000);

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ConversationId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            AuthorId = "6a1253ea-c5ec-496f-a4c4-b984e20f9507",
                            ConversationId = -1,
                            Text = "Hello Sara and Bertil my name is John!",
                            Time = new DateTime(2022, 8, 19, 22, 26, 48, 808, DateTimeKind.Local).AddTicks(3626)
                        },
                        new
                        {
                            Id = -2,
                            AuthorId = "73cb7202-145f-42cb-867e-a9082bbfeb94",
                            ConversationId = -1,
                            Text = "Hello John!",
                            Time = new DateTime(2022, 8, 20, 22, 26, 48, 808, DateTimeKind.Local).AddTicks(4412)
                        },
                        new
                        {
                            Id = -3,
                            AuthorId = "a27dfaaa-183e-46ab-aade-65c082a16a2e",
                            ConversationId = -2,
                            Text = "What's up??",
                            Time = new DateTime(2022, 8, 21, 22, 26, 48, 808, DateTimeKind.Local).AddTicks(4444)
                        },
                        new
                        {
                            Id = -4,
                            AuthorId = "6a1253ea-c5ec-496f-a4c4-b984e20f9507",
                            ConversationId = -2,
                            Text = "Umm..",
                            Time = new DateTime(2022, 8, 21, 22, 26, 48, 808, DateTimeKind.Local).AddTicks(4448)
                        },
                        new
                        {
                            Id = -5,
                            AuthorId = "a27dfaaa-183e-46ab-aade-65c082a16a2e",
                            ConversationId = -3,
                            Text = "Message from Bertil to Sara",
                            Time = new DateTime(2022, 8, 21, 22, 26, 48, 808, DateTimeKind.Local).AddTicks(4452)
                        });
                });

            modelBuilder.Entity("Group3.Models.Picture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Pictures");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Path = "admin@fakemail.net/picture1.jpg",
                            UserId = "6a1253ea-c5ec-496f-a4c4-b984e20f9507"
                        },
                        new
                        {
                            Id = -2,
                            Path = "sara@fakemail.net/picture2.jpg",
                            UserId = "73cb7202-145f-42cb-867e-a9082bbfeb94"
                        },
                        new
                        {
                            Id = -3,
                            Path = "bertil@fakemail.net/picture3.jpg",
                            UserId = "a27dfaaa-183e-46ab-aade-65c082a16a2e"
                        });
                });

            modelBuilder.Entity("Group3.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Reports")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(10000);

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<int>("Votes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            AuthorId = "73cb7202-145f-42cb-867e-a9082bbfeb94",
                            Reports = 0,
                            SubjectId = -2,
                            Text = "Is this version any good?",
                            Time = new DateTime(2022, 8, 20, 22, 26, 48, 805, DateTimeKind.Local).AddTicks(5225),
                            Votes = 1
                        },
                        new
                        {
                            Id = -2,
                            AuthorId = "6a1253ea-c5ec-496f-a4c4-b984e20f9507",
                            Reports = 2,
                            SubjectId = -2,
                            Text = "Maybe, but I'll stick with 2019!",
                            Time = new DateTime(2022, 8, 21, 22, 26, 48, 807, DateTimeKind.Local).AddTicks(9398),
                            Votes = 0
                        },
                        new
                        {
                            Id = -3,
                            AuthorId = "6a1253ea-c5ec-496f-a4c4-b984e20f9507",
                            Reports = 0,
                            SubjectId = -1,
                            Text = "How do I make a <b>table?</b>",
                            Time = new DateTime(2022, 8, 17, 22, 26, 48, 807, DateTimeKind.Local).AddTicks(9488),
                            Votes = 3
                        },
                        new
                        {
                            Id = -4,
                            AuthorId = "73cb7202-145f-42cb-867e-a9082bbfeb94",
                            Reports = 1,
                            SubjectId = -1,
                            Text = "I dont know..",
                            Time = new DateTime(2022, 8, 18, 22, 26, 48, 807, DateTimeKind.Local).AddTicks(9495),
                            Votes = 0
                        },
                        new
                        {
                            Id = -5,
                            AuthorId = "a27dfaaa-183e-46ab-aade-65c082a16a2e",
                            Reports = 0,
                            SubjectId = -1,
                            Text = "Me neither..",
                            Time = new DateTime(2022, 8, 22, 19, 26, 48, 807, DateTimeKind.Local).AddTicks(9499),
                            Votes = 1
                        },
                        new
                        {
                            Id = -6,
                            AuthorId = "73cb7202-145f-42cb-867e-a9082bbfeb94",
                            Reports = 0,
                            SubjectId = -3,
                            Text = "WoW first post?!?",
                            Time = new DateTime(2019, 8, 22, 22, 26, 48, 807, DateTimeKind.Local).AddTicks(9520),
                            Votes = 1
                        },
                        new
                        {
                            Id = -7,
                            AuthorId = "6a1253ea-c5ec-496f-a4c4-b984e20f9507",
                            EventDate = new DateTime(2022, 8, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            Reports = 0,
                            SubjectId = -4,
                            Text = "Day for site launch. We will see if it is possible to host the site on freeasphosting.net",
                            Time = new DateTime(2022, 8, 15, 22, 26, 48, 807, DateTimeKind.Local).AddTicks(9552),
                            Votes = 0
                        },
                        new
                        {
                            Id = -8,
                            AuthorId = "6a1253ea-c5ec-496f-a4c4-b984e20f9507",
                            EventDate = new DateTime(2022, 8, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Reports = 0,
                            SubjectId = -5,
                            Text = "Day for presentation. Our project was to create a community portal for an organization, including a news feed, events, member lists and discussion forums. ",
                            Time = new DateTime(2022, 8, 15, 22, 26, 48, 807, DateTimeKind.Local).AddTicks(9969),
                            Votes = 0
                        },
                        new
                        {
                            Id = -9,
                            AuthorId = "73cb7202-145f-42cb-867e-a9082bbfeb94",
                            Reports = 0,
                            SubjectId = -6,
                            Text = "What should we talk about in our user group test forum?",
                            Time = new DateTime(2022, 8, 20, 22, 26, 48, 808, DateTimeKind.Local),
                            Votes = 0
                        },
                        new
                        {
                            Id = -10,
                            AuthorId = "a27dfaaa-183e-46ab-aade-65c082a16a2e",
                            Reports = 0,
                            SubjectId = -6,
                            Text = "Anything.",
                            Time = new DateTime(2022, 8, 21, 22, 26, 48, 808, DateTimeKind.Local).AddTicks(4),
                            Votes = 0
                        },
                        new
                        {
                            Id = -11,
                            AuthorId = "6a1253ea-c5ec-496f-a4c4-b984e20f9507",
                            EventDate = new DateTime(2022, 8, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Reports = 0,
                            SubjectId = -7,
                            Text = "We will celebrate the completion of  our studies with a Say Hello Party on Tuesday 2022-08-23. We're starting a new category that we're naming Other. In that category, we create a topic that we call random talk. In that topic we start a 'Say Hello Party' subject. We will invite the students in the other groups to our forum. If they want, they can register and can contribute a hello in our 'Say Hello Party'.",
                            Time = new DateTime(2022, 8, 16, 22, 26, 48, 808, DateTimeKind.Local).AddTicks(8),
                            Votes = 0
                        });
                });

            modelBuilder.Entity("Group3.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.Property<string>("UrlSlug")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TopicId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Name = "HTML Tables?",
                            TopicId = -2
                        },
                        new
                        {
                            Id = -2,
                            Name = "Visual Studio 2022",
                            TopicId = -1,
                            UrlSlug = "Visual-Studio-2022"
                        },
                        new
                        {
                            Id = -3,
                            Name = "Am I'm the chosen one?",
                            TopicId = -3
                        },
                        new
                        {
                            Id = -4,
                            Name = "Site launch",
                            TopicId = -5,
                            UrlSlug = "Site-launch"
                        },
                        new
                        {
                            Id = -5,
                            Name = "Site presentation",
                            TopicId = -5,
                            UrlSlug = "Site-presentation"
                        },
                        new
                        {
                            Id = -6,
                            Name = "What?.",
                            TopicId = -6
                        },
                        new
                        {
                            Id = -7,
                            Name = "Say Hello Party",
                            TopicId = -5,
                            UrlSlug = "Say-Hello-Party"
                        });
                });

            modelBuilder.Entity("Group3.Models.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CategoryId = -1,
                            Description = "What's hot right now?",
                            Name = "Trending"
                        },
                        new
                        {
                            Id = -2,
                            CategoryId = -2,
                            Description = "Tag TAG <b>TAG!</b>",
                            Name = "HTML"
                        },
                        new
                        {
                            Id = -3,
                            CategoryId = -2,
                            Description = "The necessary evil?",
                            Name = "CSS"
                        },
                        new
                        {
                            Id = -4,
                            CategoryId = -3,
                            Description = "Because SQL is even worse.",
                            Name = "Entity Framework"
                        },
                        new
                        {
                            Id = -5,
                            CategoryId = -1,
                            Description = "Planned occasions.",
                            Name = "Events"
                        },
                        new
                        {
                            Id = -6,
                            CategoryId = -4,
                            Description = "For random testing.",
                            Name = "User Group Test"
                        },
                        new
                        {
                            Id = -7,
                            CategoryId = -1,
                            Description = "Backend news",
                            Name = "Backend"
                        },
                        new
                        {
                            Id = -8,
                            CategoryId = -1,
                            Description = "News about frontend subjects",
                            Name = "Frontend"
                        },
                        new
                        {
                            Id = -9,
                            CategoryId = -1,
                            Description = "Other news",
                            Name = "Other"
                        },
                        new
                        {
                            Id = -10,
                            CategoryId = -5,
                            Description = "A 3D computer graphics game engine developed by Epic Games.",
                            Name = "Unreal Engine"
                        },
                        new
                        {
                            Id = -11,
                            CategoryId = -6,
                            Description = "About developing this very forum.",
                            Name = "This Forum"
                        },
                        new
                        {
                            Id = -12,
                            CategoryId = -7,
                            Description = "Computer games.",
                            Name = "Games"
                        },
                        new
                        {
                            Id = -13,
                            CategoryId = -7,
                            Description = "Where we can talk about anything.",
                            Name = "Random Talk"
                        });
                });

            modelBuilder.Entity("Group3.Models.UserGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("CategoryId")
                        .IsUnique();

                    b.ToTable("UserGroups");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CategoryId = -4
                        });
                });

            modelBuilder.Entity("Group3.Models.UserGroupEnlistment", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserGroupId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("UserId", "UserGroupId");

                    b.HasIndex("UserGroupId");

                    b.ToTable("UserGroupEnlistments");

                    b.HasData(
                        new
                        {
                            UserId = "6a1253ea-c5ec-496f-a4c4-b984e20f9507",
                            UserGroupId = -1,
                            Id = -1
                        },
                        new
                        {
                            UserId = "a27dfaaa-183e-46ab-aade-65c082a16a2e",
                            UserGroupId = -1,
                            Id = -2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Group3.Models.ApplicationUserRole", b =>
                {
                    b.HasOne("Group3.Models.ApplicationRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Group3.Models.ApplicationUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Group3.Models.ConversationParticipation", b =>
                {
                    b.HasOne("Group3.Models.Conversation", "Conversation")
                        .WithMany("ConversationParticipations")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Group3.Models.ApplicationUser", "User")
                        .WithMany("ConversationParticipations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Group3.Models.Message", b =>
                {
                    b.HasOne("Group3.Models.ApplicationUser", "Author")
                        .WithMany("Messages")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Group3.Models.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Group3.Models.Picture", b =>
                {
                    b.HasOne("Group3.Models.Post", null)
                        .WithMany("Pictures")
                        .HasForeignKey("PostId");

                    b.HasOne("Group3.Models.ApplicationUser", "User")
                        .WithMany("Pictures")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Group3.Models.Post", b =>
                {
                    b.HasOne("Group3.Models.ApplicationUser", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Group3.Models.Subject", "Subject")
                        .WithMany("Posts")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Group3.Models.Subject", b =>
                {
                    b.HasOne("Group3.Models.Topic", "Topic")
                        .WithMany("Subjects")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Group3.Models.Topic", b =>
                {
                    b.HasOne("Group3.Models.Category", "Category")
                        .WithMany("Topics")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Group3.Models.UserGroup", b =>
                {
                    b.HasOne("Group3.Models.ApplicationUser", null)
                        .WithMany("UserGroups")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("Group3.Models.Category", "Category")
                        .WithOne("UserGroup")
                        .HasForeignKey("Group3.Models.UserGroup", "CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Group3.Models.UserGroupEnlistment", b =>
                {
                    b.HasOne("Group3.Models.UserGroup", "UserGroup")
                        .WithMany("UserGroupEnlistments")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Group3.Models.ApplicationUser", "User")
                        .WithMany("UserGroupEnlistments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Group3.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Group3.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Group3.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Group3.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
