// <auto-generated />
using System;
using Group3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Group3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220821201647_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Group3.Models.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "a58e458f-2945-4cad-94c5-1028f7110590",
                            ConcurrencyStamp = "18367f50-83c1-4e82-9c48-7cc40ecdc518",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "93603bd9-65d6-4907-ac82-c125e2e1a2f5",
                            ConcurrencyStamp = "e0fa134b-8685-4676-b55f-02d9011ae4a5",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "c2daeab1-dfdb-474b-9755-f089c01c8fcd",
                            ConcurrencyStamp = "d3fce48c-06f0-44df-9b23-ff5afde6633d",
                            Name = "Moderator",
                            NormalizedName = "MODERATOR"
                        });
                });

            modelBuilder.Entity("Group3.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "c399a4e0-286f-4750-bd7e-f40c86bdfaa7",
                            AccessFailedCount = 0,
                            Birthdate = new DateTime(1964, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "5ab34ac7-e381-4b98-a3e9-53e7157611cd",
                            Email = "admin@fakemail.net",
                            EmailConfirmed = false,
                            FirstName = "John",
                            LastName = "Doe",
                            Location = "America",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@FAKEMAIL.NET",
                            NormalizedUserName = "ADMIN@FAKEMAIL.NET",
                            PasswordHash = "AQAAAAEAACcQAAAAEPBiOBY0+nHlhsZ9cIXOFKGZbXm+FAlXccXLhUpRVG3/9tDJJ52X9ic2R1HK8qd0fg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e4d50f2c-359e-4817-86a3-e360b2388fb9",
                            TwoFactorEnabled = false,
                            UserName = "admin@fakemail.net"
                        },
                        new
                        {
                            Id = "ce7d56d0-af41-4c7a-922e-bf98f4f22cad",
                            AccessFailedCount = 0,
                            Birthdate = new DateTime(1993, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "499846c3-d818-425d-8779-1e0bb79aee77",
                            Email = "sara@fakemail.net",
                            EmailConfirmed = false,
                            FirstName = "Sara",
                            LastName = "Svensson",
                            Location = "Danmark",
                            LockoutEnabled = false,
                            NormalizedEmail = "SARA@FAKEMAIL.NET",
                            NormalizedUserName = "SARA@FAKEMAIL.NET",
                            PasswordHash = "AQAAAAEAACcQAAAAEP5FrcFkYnWG2THiBsxV7p9oyYegi82crVjFYDHoZfvxmZLroQDSeJVPNWE6DZpxLw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bb1fc9f1-5a54-4c18-acb6-7be801f33634",
                            TwoFactorEnabled = false,
                            UserName = "sara@fakemail.net"
                        },
                        new
                        {
                            Id = "5f89f8bb-742f-4fdf-9a50-3431742816ea",
                            AccessFailedCount = 0,
                            Birthdate = new DateTime(1985, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ConcurrencyStamp = "ffe37309-2c36-48be-a7b8-adff441bc488",
                            Email = "bertil@fakemail.net",
                            EmailConfirmed = false,
                            FirstName = "Bertil",
                            LastName = "Johansson",
                            Location = "Sweden",
                            LockoutEnabled = false,
                            NormalizedEmail = "BERTIL@FAKEMAIL.NET",
                            NormalizedUserName = "BERTIL@FAKEMAIL.NET",
                            PasswordHash = "AQAAAAEAACcQAAAAEER/fw+/aFlFUdpJDr9/eZEF+PzhVYc1WCXpWsnYq3ZdrdedgrjQyjU7SS5ZkERC1g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "485f1296-6214-4ffd-9a13-ea23f3a41033",
                            TwoFactorEnabled = false,
                            UserName = "bertil@fakemail.net"
                        });
                });

            modelBuilder.Entity("Group3.Models.ApplicationUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "c399a4e0-286f-4750-bd7e-f40c86bdfaa7",
                            RoleId = "a58e458f-2945-4cad-94c5-1028f7110590"
                        },
                        new
                        {
                            UserId = "ce7d56d0-af41-4c7a-922e-bf98f4f22cad",
                            RoleId = "93603bd9-65d6-4907-ac82-c125e2e1a2f5"
                        },
                        new
                        {
                            UserId = "5f89f8bb-742f-4fdf-9a50-3431742816ea",
                            RoleId = "c2daeab1-dfdb-474b-9755-f089c01c8fcd"
                        });
                });

            modelBuilder.Entity("Group3.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("UserGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Description = "Breaking news here!",
                            Name = "News",
                            UserGroupId = 0
                        },
                        new
                        {
                            Id = -2,
                            Description = "Javascript, React and more.",
                            Name = "Frontend",
                            UserGroupId = 0
                        },
                        new
                        {
                            Id = -3,
                            Description = "C++ and C#",
                            Name = "Backend",
                            UserGroupId = 0
                        },
                        new
                        {
                            Id = -4,
                            Description = "En grupp av testare.",
                            Name = "Testgruppen",
                            UserGroupId = 0
                        });
                });

            modelBuilder.Entity("Group3.Models.Chat", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("MessageId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("UserId", "MessageId");

                    b.HasIndex("MessageId");

                    b.ToTable("Chats");

                    b.HasData(
                        new
                        {
                            UserId = "c399a4e0-286f-4750-bd7e-f40c86bdfaa7",
                            MessageId = -1,
                            Id = -1
                        },
                        new
                        {
                            UserId = "ce7d56d0-af41-4c7a-922e-bf98f4f22cad",
                            MessageId = -1,
                            Id = -1
                        },
                        new
                        {
                            UserId = "5f89f8bb-742f-4fdf-9a50-3431742816ea",
                            MessageId = -1,
                            Id = -1
                        },
                        new
                        {
                            UserId = "c399a4e0-286f-4750-bd7e-f40c86bdfaa7",
                            MessageId = -2,
                            Id = -1
                        },
                        new
                        {
                            UserId = "ce7d56d0-af41-4c7a-922e-bf98f4f22cad",
                            MessageId = -2,
                            Id = -1
                        },
                        new
                        {
                            UserId = "5f89f8bb-742f-4fdf-9a50-3431742816ea",
                            MessageId = -2,
                            Id = -1
                        },
                        new
                        {
                            UserId = "c399a4e0-286f-4750-bd7e-f40c86bdfaa7",
                            MessageId = -3,
                            Id = -2
                        },
                        new
                        {
                            UserId = "ce7d56d0-af41-4c7a-922e-bf98f4f22cad",
                            MessageId = -3,
                            Id = -2
                        },
                        new
                        {
                            UserId = "5f89f8bb-742f-4fdf-9a50-3431742816ea",
                            MessageId = -3,
                            Id = -2
                        },
                        new
                        {
                            UserId = "c399a4e0-286f-4750-bd7e-f40c86bdfaa7",
                            MessageId = -4,
                            Id = -2
                        },
                        new
                        {
                            UserId = "ce7d56d0-af41-4c7a-922e-bf98f4f22cad",
                            MessageId = -4,
                            Id = -2
                        },
                        new
                        {
                            UserId = "5f89f8bb-742f-4fdf-9a50-3431742816ea",
                            MessageId = -4,
                            Id = -2
                        },
                        new
                        {
                            UserId = "ce7d56d0-af41-4c7a-922e-bf98f4f22cad",
                            MessageId = -5,
                            Id = -3
                        },
                        new
                        {
                            UserId = "5f89f8bb-742f-4fdf-9a50-3431742816ea",
                            MessageId = -5,
                            Id = -3
                        });
                });

            modelBuilder.Entity("Group3.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(10000);

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            AuthorId = "c399a4e0-286f-4750-bd7e-f40c86bdfaa7",
                            Text = "Hello Sara and Bertil my name is John!",
                            Time = new DateTime(2022, 8, 18, 22, 16, 46, 881, DateTimeKind.Local).AddTicks(2063)
                        },
                        new
                        {
                            Id = -2,
                            AuthorId = "ce7d56d0-af41-4c7a-922e-bf98f4f22cad",
                            Text = "Hello John!",
                            Time = new DateTime(2022, 8, 19, 22, 16, 46, 881, DateTimeKind.Local).AddTicks(2817)
                        },
                        new
                        {
                            Id = -3,
                            AuthorId = "5f89f8bb-742f-4fdf-9a50-3431742816ea",
                            Text = "What's up??",
                            Time = new DateTime(2022, 8, 20, 22, 16, 46, 881, DateTimeKind.Local).AddTicks(2846)
                        },
                        new
                        {
                            Id = -4,
                            AuthorId = "c399a4e0-286f-4750-bd7e-f40c86bdfaa7",
                            Text = "Umm..",
                            Time = new DateTime(2022, 8, 20, 22, 16, 46, 881, DateTimeKind.Local).AddTicks(2850)
                        },
                        new
                        {
                            Id = -5,
                            AuthorId = "5f89f8bb-742f-4fdf-9a50-3431742816ea",
                            Text = "Message from Bertil to Sara",
                            Time = new DateTime(2022, 8, 20, 22, 16, 46, 881, DateTimeKind.Local).AddTicks(2854)
                        });
                });

            modelBuilder.Entity("Group3.Models.Picture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("Pictures");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Path = "admin@fakemail.net/picture1.jpg",
                            UserId = "c399a4e0-286f-4750-bd7e-f40c86bdfaa7"
                        },
                        new
                        {
                            Id = -2,
                            Path = "sara@fakemail.net/picture2.jpg",
                            UserId = "ce7d56d0-af41-4c7a-922e-bf98f4f22cad"
                        },
                        new
                        {
                            Id = -3,
                            Path = "bertil@fakemail.net/picture3.jpg",
                            UserId = "5f89f8bb-742f-4fdf-9a50-3431742816ea"
                        });
                });

            modelBuilder.Entity("Group3.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Reports")
                        .HasColumnType("int");

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(10000);

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<int>("Votes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            AuthorId = "ce7d56d0-af41-4c7a-922e-bf98f4f22cad",
                            Reports = 0,
                            SubjectId = -2,
                            Text = "Is this version any good?",
                            Time = new DateTime(2022, 8, 19, 22, 16, 46, 876, DateTimeKind.Local).AddTicks(6699),
                            Votes = 1
                        },
                        new
                        {
                            Id = -2,
                            AuthorId = "c399a4e0-286f-4750-bd7e-f40c86bdfaa7",
                            Reports = 2,
                            SubjectId = -2,
                            Text = "Maybe, but I'll stick with 2019!",
                            Time = new DateTime(2022, 8, 20, 22, 16, 46, 880, DateTimeKind.Local).AddTicks(9575),
                            Votes = 0
                        },
                        new
                        {
                            Id = -3,
                            AuthorId = "c399a4e0-286f-4750-bd7e-f40c86bdfaa7",
                            Reports = 0,
                            SubjectId = -1,
                            Text = "How do I make a <b>table?</b>",
                            Time = new DateTime(2022, 8, 16, 22, 16, 46, 880, DateTimeKind.Local).AddTicks(9673),
                            Votes = 3
                        },
                        new
                        {
                            Id = -4,
                            AuthorId = "ce7d56d0-af41-4c7a-922e-bf98f4f22cad",
                            Reports = 1,
                            SubjectId = -1,
                            Text = "I dont know..",
                            Time = new DateTime(2022, 8, 17, 22, 16, 46, 880, DateTimeKind.Local).AddTicks(9680),
                            Votes = 0
                        },
                        new
                        {
                            Id = -5,
                            AuthorId = "5f89f8bb-742f-4fdf-9a50-3431742816ea",
                            Reports = 0,
                            SubjectId = -1,
                            Text = "Me neither..",
                            Time = new DateTime(2022, 8, 21, 19, 16, 46, 880, DateTimeKind.Local).AddTicks(9684),
                            Votes = 1
                        },
                        new
                        {
                            Id = -6,
                            AuthorId = "ce7d56d0-af41-4c7a-922e-bf98f4f22cad",
                            Reports = 0,
                            SubjectId = -3,
                            Text = "WoW first post?!?",
                            Time = new DateTime(2019, 8, 21, 22, 16, 46, 880, DateTimeKind.Local).AddTicks(9705),
                            Votes = 1
                        },
                        new
                        {
                            Id = -7,
                            AuthorId = "c399a4e0-286f-4750-bd7e-f40c86bdfaa7",
                            EventDate = new DateTime(2022, 8, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            Reports = 0,
                            SubjectId = -4,
                            Text = "Day for site launch. We will see if it is possible to host the site on freeasphosting.net",
                            Time = new DateTime(2022, 8, 14, 22, 16, 46, 880, DateTimeKind.Local).AddTicks(9741),
                            Votes = 0
                        },
                        new
                        {
                            Id = -8,
                            AuthorId = "c399a4e0-286f-4750-bd7e-f40c86bdfaa7",
                            EventDate = new DateTime(2022, 9, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            Reports = 0,
                            SubjectId = -5,
                            Text = "Day for presentation. Our project was to create a community portal for an organization, including a news feed, events, member lists and discussion forums. ",
                            Time = new DateTime(2022, 8, 14, 22, 16, 46, 881, DateTimeKind.Local).AddTicks(177),
                            Votes = 0
                        },
                        new
                        {
                            Id = -9,
                            AuthorId = "ce7d56d0-af41-4c7a-922e-bf98f4f22cad",
                            Reports = 0,
                            SubjectId = -6,
                            Text = "What should we talk about in our user group test forum?",
                            Time = new DateTime(2022, 8, 19, 22, 16, 46, 881, DateTimeKind.Local).AddTicks(207),
                            Votes = 0
                        },
                        new
                        {
                            Id = -10,
                            AuthorId = "5f89f8bb-742f-4fdf-9a50-3431742816ea",
                            Reports = 0,
                            SubjectId = -6,
                            Text = "Anything.",
                            Time = new DateTime(2022, 8, 20, 22, 16, 46, 881, DateTimeKind.Local).AddTicks(211),
                            Votes = 0
                        });
                });

            modelBuilder.Entity("Group3.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.Property<string>("UrlSlug")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("TopicId");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            AuthorId = "c399a4e0-286f-4750-bd7e-f40c86bdfaa7",
                            Name = "HTML Tables?",
                            TopicId = -2
                        },
                        new
                        {
                            Id = -2,
                            AuthorId = "ce7d56d0-af41-4c7a-922e-bf98f4f22cad",
                            Name = "Visual Studio 2022",
                            TopicId = -1,
                            UrlSlug = "Visual-Studio-2022"
                        },
                        new
                        {
                            Id = -3,
                            AuthorId = "ce7d56d0-af41-4c7a-922e-bf98f4f22cad",
                            Name = "Am I'm the chosen one?",
                            TopicId = -3
                        },
                        new
                        {
                            Id = -4,
                            AuthorId = "c399a4e0-286f-4750-bd7e-f40c86bdfaa7",
                            Name = "Site launch",
                            TopicId = -5,
                            UrlSlug = "Site-launch"
                        },
                        new
                        {
                            Id = -5,
                            AuthorId = "c399a4e0-286f-4750-bd7e-f40c86bdfaa7",
                            Name = "Site presentation",
                            TopicId = -5,
                            UrlSlug = "Site-presentation"
                        },
                        new
                        {
                            Id = -6,
                            AuthorId = "ce7d56d0-af41-4c7a-922e-bf98f4f22cad",
                            Name = "What?.",
                            TopicId = -6
                        });
                });

            modelBuilder.Entity("Group3.Models.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AuthorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            AuthorId = "c399a4e0-286f-4750-bd7e-f40c86bdfaa7",
                            CategoryId = -1,
                            Description = "What's hot right now?",
                            Name = "Trending"
                        },
                        new
                        {
                            Id = -2,
                            AuthorId = "c399a4e0-286f-4750-bd7e-f40c86bdfaa7",
                            CategoryId = -2,
                            Description = "Tag TAG <b>TAG!</b>",
                            Name = "HTML"
                        },
                        new
                        {
                            Id = -3,
                            AuthorId = "ce7d56d0-af41-4c7a-922e-bf98f4f22cad",
                            CategoryId = -2,
                            Description = "The necessary evil?",
                            Name = "CSS"
                        },
                        new
                        {
                            Id = -4,
                            AuthorId = "ce7d56d0-af41-4c7a-922e-bf98f4f22cad",
                            CategoryId = -3,
                            Description = "Because SQL is even worse.",
                            Name = "Entity Framework"
                        },
                        new
                        {
                            Id = -5,
                            AuthorId = "c399a4e0-286f-4750-bd7e-f40c86bdfaa7",
                            CategoryId = -1,
                            Description = "Planned occasions.",
                            Name = "Events"
                        },
                        new
                        {
                            Id = -6,
                            AuthorId = "ce7d56d0-af41-4c7a-922e-bf98f4f22cad",
                            CategoryId = -4,
                            Description = "For random testing.",
                            Name = "User Group Test"
                        },
                        new
                        {
                            Id = -7,
                            AuthorId = "c399a4e0-286f-4750-bd7e-f40c86bdfaa7",
                            CategoryId = -1,
                            Description = "Backend news",
                            Name = "Backend"
                        },
                        new
                        {
                            Id = -8,
                            AuthorId = "c399a4e0-286f-4750-bd7e-f40c86bdfaa7",
                            CategoryId = -1,
                            Description = "News about frontend subjects",
                            Name = "Frontend"
                        },
                        new
                        {
                            Id = -9,
                            AuthorId = "c399a4e0-286f-4750-bd7e-f40c86bdfaa7",
                            CategoryId = -1,
                            Description = "Other news",
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("Group3.Models.UserGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("CategoryId")
                        .IsUnique();

                    b.ToTable("UserGroups");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CategoryId = -4
                        });
                });

            modelBuilder.Entity("Group3.Models.UserGroupEnlistment", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserGroupId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("UserId", "UserGroupId");

                    b.HasIndex("UserGroupId");

                    b.ToTable("UserGroupEnlistments");

                    b.HasData(
                        new
                        {
                            UserId = "c399a4e0-286f-4750-bd7e-f40c86bdfaa7",
                            UserGroupId = -1,
                            Id = -1
                        },
                        new
                        {
                            UserId = "5f89f8bb-742f-4fdf-9a50-3431742816ea",
                            UserGroupId = -1,
                            Id = -2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Group3.Models.ApplicationUserRole", b =>
                {
                    b.HasOne("Group3.Models.ApplicationRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Group3.Models.ApplicationUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Group3.Models.Chat", b =>
                {
                    b.HasOne("Group3.Models.Message", "Message")
                        .WithMany("Chats")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Group3.Models.ApplicationUser", "User")
                        .WithMany("Chats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Group3.Models.Message", b =>
                {
                    b.HasOne("Group3.Models.ApplicationUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");
                });

            modelBuilder.Entity("Group3.Models.Picture", b =>
                {
                    b.HasOne("Group3.Models.Post", null)
                        .WithMany("Pictures")
                        .HasForeignKey("PostId");

                    b.HasOne("Group3.Models.ApplicationUser", "User")
                        .WithMany("Pictures")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Group3.Models.Post", b =>
                {
                    b.HasOne("Group3.Models.ApplicationUser", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Group3.Models.Subject", "Subject")
                        .WithMany("Posts")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Group3.Models.Subject", b =>
                {
                    b.HasOne("Group3.Models.ApplicationUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("Group3.Models.Topic", "Topic")
                        .WithMany("Subjects")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Group3.Models.Topic", b =>
                {
                    b.HasOne("Group3.Models.ApplicationUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.HasOne("Group3.Models.Category", "Category")
                        .WithMany("Topics")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Group3.Models.UserGroup", b =>
                {
                    b.HasOne("Group3.Models.ApplicationUser", null)
                        .WithMany("UserGroups")
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("Group3.Models.Category", "Category")
                        .WithOne("UserGroup")
                        .HasForeignKey("Group3.Models.UserGroup", "CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Group3.Models.UserGroupEnlistment", b =>
                {
                    b.HasOne("Group3.Models.UserGroup", "UserGroup")
                        .WithMany("UserGroupEnlistments")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Group3.Models.ApplicationUser", "User")
                        .WithMany("UserGroupEnlistments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Group3.Models.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Group3.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Group3.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Group3.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
